# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('wagtaildocs', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingType',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de creación')),
                ('details_field', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CustomerCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de creación')),
                ('details_field', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de clientes',
                'verbose_name_plural': 'Agregar Categoría de clientes',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='LodgingCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LodgingType',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de creación')),
                ('details_field', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Categoría de alojamiento',
                'verbose_name_plural': 'Agregar Categoría de alojamiento',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de creación')),
                ('details_field', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Categoría de productos',
                'verbose_name_plural': 'Agregar Categoría de productos',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SalesType',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de creación')),
                ('details_field', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'F&V',
                'verbose_name_plural': 'F&V',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SequenceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de sequencia')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('type_seq', models.CharField(choices=[('0', 'Compras'), ('1', 'Ventas'), ('2', 'Miscelaneo')], default='1', max_length=1, verbose_name='Tipo')),
                ('prefix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prefijo')),
                ('suffix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sufijo')),
                ('number_actual', models.PositiveIntegerField(default=1, help_text='Next number that will be used. This number can be incremented ', verbose_name='Número actual')),
                ('number_next', models.PositiveIntegerField(default=1, help_text='Next number of this sequence', verbose_name='Siguiente número')),
                ('number_increment', models.PositiveIntegerField(default=1, help_text='The next number of the sequence will be incremented by this number', verbose_name='Incremento')),
                ('padding', models.PositiveIntegerField(default=1, help_text='Longitud secuencial, entre el número de la secuencia y el afijo.', verbose_name='Longitud secuencial')),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
            },
        ),
        migrations.AddField(
            model_name='salestype',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='category.SequenceTypes', verbose_name='Secuencia'),
        ),
        migrations.AddField(
            model_name='lodgingcarouselitem',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
