# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20160603_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roottree',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
