# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
        ('category', '0002_auto_20160528_0138'),
        ('lodging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Plazo de pago',
                'verbose_name_plural': 'Plazos de pagos',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('parent_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.SalesType')),
                ('sale_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de venta')),
                ('accounting_date', models.DateField(default=datetime.date.today, verbose_name='Fecha contable')),
                ('sale_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Orden de venta')),
                ('invoice_ncf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de comprobante')),
                ('sale_state', models.IntegerField(choices=[(1, 'Presupuesto'), (2, 'Abierto'), (3, 'Pagado'), (4, 'Cancelado'), (5, 'Crédito')], default=1, verbose_name='Estado')),
                ('sub_total', models.FloatField(blank=True, null=True, verbose_name='Sub Total Venta')),
                ('sale_taxes', models.FloatField(blank=True, null=True, verbose_name='Impuestos')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='Total Venta')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'V&F',
                'verbose_name_plural': 'V&F',
            },
            bases=('category.salestype',),
        ),
        migrations.CreateModel(
            name='SaleProductInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.IntegerField(choices=[(0, 'Hoteles'), (1, 'Restaurantes')], default='0', null=True, verbose_name='Clasificación')),
                ('apply_discount', models.BooleanField(default=False, verbose_name='Tiene descuento?')),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'Monto Fijo'), ('percent', 'Porcentaje')], max_length=1, null=True, verbose_name='Tipo de descuento')),
                ('num_of_adults', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, verbose_name='Adultos')),
                ('num_of_children', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Niños')),
                ('child_num_1_age', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)], default=0, verbose_name='Edad')),
                ('child_num_2_age', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)], default=0, verbose_name='Edad')),
                ('child_num_3_age', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)], default=0, verbose_name='Edad')),
                ('arrival_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Llegada')),
                ('duration', models.IntegerField(choices=[(1, '1 Noche'), (2, '2 Noches'), (3, '3 Noches'), (4, '4 Noches'), (5, '5 Noches'), (6, '6 Noches'), (7, '7 Noches'), (8, '8 Noches'), (9, '9 Noches'), (10, '10 Noches'), (11, '11 Noches'), (12, '12 Noches'), (13, '13 Noches'), (14, '14 Noches'), (15, '15 Noches')], default=1, verbose_name='Duración')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Descuento')),
                ('sale_qty', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, verbose_name='# De Hab.')),
                ('sale_price', models.FloatField(blank=True, null=True, verbose_name='Precio')),
                ('sub_total_inline', models.FloatField(blank=True, null=True, verbose_name='Sub-total')),
                ('total_amount_inline', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('product_sale_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.Product', verbose_name='Tipo de habitación')),
                ('sale_inline', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_inline_rels', to='sales.Sale')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lodging.Lodging', verbose_name='Alojamiento')),
            ],
        ),
        migrations.CreateModel(
            name='TaxSaleRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.ProductTax', verbose_name='Impuesto')),
                ('sales', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_sale_rel', to='sales.Sale')),
            ],
        ),
    ]
