# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproductinline',
            name='product_sale_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='saleproductinline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lodging.Lodging', verbose_name='Suplidor'),
        ),
    ]
