# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160603_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='inline_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_lodging_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_lodging_rel', to='lodging.Lodging', verbose_name='Proveedor'),
        ),
    ]
